### ISSUE TITLE
Tailwindcss support to components library.

### ISSUE THREAD

**Issue by ruzolut** [rofazayn/laafya#21]
Tailwindcss is a modern css library, it has built-in css utilities dedicated to style your app faster, highly recommended for this project's components library.

**Comment by rofazayn** [comment]
I had an idea before of using react-native-web to share UI components between the web and mobile apps, but unfortunately Tailwindcss doesn't support it, so we have a bit of an issue here, wether we should use Tailwindcss or perhaps styled-componenets.

**Comment by rofazayn** [comment]
It's decided. Tailwind will not be added directly to the web package, instead it will be available on a separate standalone package of components.

Title of the issue and description will be updated!

**Comment by rofazayn** [comment]
After second thought, maybe I should add it to the web package instead of a standalone components package.
